import type { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    id: 'prod-coffee-maker',
    slug: 'premium-coffee-maker',
    name: 'Premium Coffee Maker',
    shortDescription: 'A polished brewer with precision temperature control.',
    description:
      'Designed for coffee lovers who want rich flavor and a premium finish in the kitchen.',
    category: 'Coffee Makers',
    parentCategory: 'Home & Kitchen',
    brand: 'Northstar',
    tags: ['featured', 'kitchen', 'new'],
    price: 89.99,
    compareAtPrice: 119.99,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 245,
    reviewSummary: 'Excellent brew quality and premium build.',
    images: [{ src: '☕', alt: 'Premium coffee maker' }],
    inventoryStatus: 'in_stock',
    inventoryCount: 42,
    isFeatured: true,
    isOnSale: true,
    discountPercent: 25,
    isBestSeller: true,
    createdAt: '2026-06-24',
    variants: [
      { id: 'cm-black', name: 'Black', sku: 'CM-001', price: 89.99, stockStatus: 'in_stock', attributes: { color: 'Black' } },
      { id: 'cm-silver', name: 'Silver', sku: 'CM-002', price: 99.99, stockStatus: 'low_stock', attributes: { color: 'Silver' } },
    ],
    reviews: [
      {
        id: 'rev-1',
        author: 'Mina',
        rating: 5,
        title: 'Beautiful and reliable',
        comment: 'The brewing is consistent and the finish looks great on the counter.',
        createdAt: '2025-02-10',
      },
    ],
  },
  {
    id: 'prod-smart-watch',
    slug: 'smart-watch-pro',
    name: 'Smart Watch Pro',
    shortDescription: 'Lightweight tracking and health insights in one device.',
    description:
      'A feature-rich watch built for everyday activity tracking, sleep monitoring, and notifications.',
    category: 'Wearables',
    parentCategory: 'Electronics',
    brand: 'Pulse',
    tags: ['featured', 'wearables'],
    price: 199.99,
    compareAtPrice: 249.99,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 328,
    reviewSummary: 'Great battery life and helpful wellness tracking.',
    images: [{ src: '⌚', alt: 'Smart watch' }],
    inventoryStatus: 'low_stock',
    inventoryCount: 8,
    isFeatured: true,
    isOnSale: true,
    discountPercent: 20,
    isBestSeller: true,
    createdAt: '2026-07-01',
  },
  {
    id: 'prod-speaker',
    slug: 'portable-speaker',
    name: 'Portable Speaker',
    shortDescription: 'Rich audio with deep bass for travel and gatherings.',
    description: 'Take your sound anywhere with a rugged, waterproof design and long battery life.',
    category: 'Speakers',
    parentCategory: 'Audio',
    brand: 'Echo',
    tags: ['audio', 'travel'],
    price: 49.99,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 412,
    reviewSummary: 'Excellent sound for the price.',
    images: [{ src: '🔊', alt: 'Portable speaker' }],
    inventoryStatus: 'in_stock',
    inventoryCount: 27,
    isFeatured: true,
    isOnSale: false,
    isBestSeller: false,
    createdAt: '2026-05-12',
  },
  {
    id: 'prod-yoga-mat',
    slug: 'premium-yoga-mat',
    name: 'Premium Yoga Mat',
    shortDescription: 'A supportive, non-slip mat for daily workouts.',
    description: 'Comfortable cushioning and grip that stay reliable through every session.',
    category: 'Yoga Mats',
    parentCategory: 'Fitness',
    brand: 'Flow',
    tags: ['fitness', 'wellness'],
    price: 29.99,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 156,
    reviewSummary: 'Excellent grip and comfort.',
    images: [{ src: '🧘', alt: 'Yoga mat' }],
    inventoryStatus: 'in_stock',
    inventoryCount: 61,
    isFeatured: false,
    isOnSale: false,
    isBestSeller: false,
    createdAt: '2026-03-22',
  },
  {
    id: 'prod-tripod',
    slug: 'camera-tripod',
    name: 'Camera Tripod',
    shortDescription: 'Compact and stable for mobile creators and photographers.',
    description: 'A versatile tripod with quick adjustments for content creation on the go.',
    category: 'Tripods',
    parentCategory: 'Photography',
    brand: 'Frame',
    tags: ['featured', 'photo'],
    price: 34.99,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 289,
    reviewSummary: 'Great stability for the money.',
    images: [{ src: '📷', alt: 'Camera tripod' }],
    inventoryStatus: 'in_stock',
    inventoryCount: 18,
    isFeatured: true,
    isOnSale: false,
    isBestSeller: true,
    createdAt: '2026-06-11',
  },
  {
    id: 'prod-charger',
    slug: 'phone-charger-fast',
    name: 'Fast Phone Charger',
    shortDescription: 'High-speed charging for phones, earbuds, and tablets.',
    description: 'Stay powered up with a compact charger that supports multiple devices.',
    category: 'Chargers',
    parentCategory: 'Electronics',
    brand: 'Volt',
    tags: ['electronics', 'accessories'],
    price: 19.99,
    currency: 'USD',
    rating: 4.4,
    reviewCount: 567,
    reviewSummary: 'Quick and dependable charging.',
    images: [{ src: '🔋', alt: 'Phone charger' }],
    inventoryStatus: 'out_of_stock',
    inventoryCount: 0,
    isFeatured: false,
    isOnSale: true,
    discountPercent: 15,
    isBestSeller: false,
    createdAt: '2026-04-03',
  },
];

export function getMockProducts(): Product[] {
  return mockProducts;
}

export function getFeaturedProducts(limit = 8): Product[] {
  return mockProducts.filter((product) => product.isFeatured).slice(0, limit);
}

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((product) => product.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return mockProducts.filter((product) => product.category === category);
}
